import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Nav from "./components/ui/Nav";
import StoreProvider from "./utils/StoreProvider";

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-red-hat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHat.variable} antialiased bg-white p-5 overflow-hidden`}
      >
        <Nav />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
